/**
 * Production Fallback Service
 *
 * This service provides hardcoded default data for production
 * when database/API endpoints are not available.
 * This ensures the website always displays content.
 */

export const DEFAULT_PROPERTIES = {
  '1': {
    id: '1',
    name: 'Artist Loft',
    slug: 'artist-loft',
    type: 'loft',
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    size: '60',
    description: 'Step into creative inspiration at this unique artist loft in Iloilo\'s vibrant Arts District. This spacious, light-filled space combines industrial charm with artistic flair.',
    short_description: 'Unique artist loft with high ceilings and natural light in the Arts District.',
    location: 'Arts District, Iloilo City',
    pricePerNight: '3000',
    airbnbUrl: 'https://airbnb.com/rooms/artist-loft',
    featured: true,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Smart TV', 'High Ceilings', 'Natural Light', 'Workspace'],
    photos: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '2': {
    id: '2',
    name: 'Garden View Suite',
    slug: 'garden-view-suite',
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    size: '50',
    description: 'Escape to this serene garden-view suite nestled in the popular Smallville Complex.',
    short_description: 'Serene garden-view suite in Smallville Complex.',
    location: 'Smallville Complex, Iloilo City',
    pricePerNight: '2800',
    airbnbUrl: 'https://airbnb.com/rooms/garden-suite',
    featured: true,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Parking', 'Kitchen', 'Balcony', 'Smart TV', 'Washer'],
    photos: [
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5f6?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '3': {
    id: '3',
    name: 'Downtown Retreat',
    slug: 'downtown-retreat',
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    maxGuests: 2,
    size: '35',
    description: 'Modern studio in the heart of Iloilo City, walking distance to SM City and major attractions.',
    short_description: 'Modern studio in downtown Iloilo City.',
    location: 'City Proper, Iloilo City',
    pricePerNight: '2200',
    airbnbUrl: 'https://airbnb.com/rooms/downtown-retreat',
    featured: true,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Smart TV', '24/7 Security'],
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '4': {
    id: '4',
    name: 'Executive Suite',
    slug: 'executive-suite',
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    size: '80',
    description: 'Luxurious executive suite perfect for business travelers and families.',
    short_description: 'Luxurious executive suite with modern amenities.',
    location: 'Iloilo Business Park',
    pricePerNight: '4500',
    airbnbUrl: 'https://airbnb.com/rooms/executive-suite',
    featured: false,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Smart TV', 'Workspace', 'Gym Access', 'Pool Access'],
    photos: [
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '5': {
    id: '5',
    name: 'Beachside Condo',
    slug: 'beachside-condo',
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 3,
    size: '45',
    description: 'Relaxing beachside condo with ocean views, perfect for a peaceful getaway.',
    short_description: 'Beachside condo with stunning ocean views.',
    location: 'Villa Beach, Iloilo City',
    pricePerNight: '3200',
    airbnbUrl: 'https://airbnb.com/rooms/beachside-condo',
    featured: false,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Balcony', 'Beach Access', 'Parking'],
    photos: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '6': {
    id: '6',
    name: 'Heritage House',
    slug: 'heritage-house',
    type: 'house',
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    size: '120',
    description: 'Charming heritage house with traditional Filipino architecture and modern comforts.',
    short_description: 'Traditional heritage house with modern amenities.',
    location: 'Jaro District, Iloilo City',
    pricePerNight: '5000',
    airbnbUrl: 'https://airbnb.com/rooms/heritage-house',
    featured: false,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Garden', 'Parking', 'Workspace'],
    photos: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '7': {
    id: '7',
    name: 'Metro Central',
    slug: 'metro-central',
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    size: '40',
    description: 'Experience the heart of Iloilo City at Metro Central, a modern accommodation in the bustling City Proper district.',
    short_description: 'Modern apartment in the heart of the city.',
    location: 'City Proper, Iloilo City',
    pricePerNight: '2200',
    airbnbUrl: 'https://airbnb.com/rooms/metro-central',
    featured: false,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Smart TV', 'Kitchen', '24/7 Security', 'Central Location'],
    photos: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '8': {
    id: '8',
    name: 'Riverside Studio',
    slug: 'riverside-studio',
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    maxGuests: 2,
    size: '35',
    description: 'Discover tranquility at Riverside Studio, a peaceful retreat along the scenic Jaro River.',
    short_description: 'Peaceful studio along the scenic river.',
    location: 'Jaro District, Iloilo City',
    pricePerNight: '2000',
    airbnbUrl: 'https://airbnb.com/rooms/riverside-studio',
    featured: false,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'River View', 'Peaceful Setting', 'Historic Area'],
    photos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '9': {
    id: '9',
    name: 'Sky Loft Penthouse',
    slug: 'sky-loft-penthouse',
    type: 'penthouse',
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    size: '100',
    description: 'Luxurious penthouse with panoramic city views and premium amenities.',
    short_description: 'Luxurious penthouse with panoramic city views.',
    location: 'Mandurriao, Iloilo City',
    pricePerNight: '6000',
    airbnbUrl: 'https://airbnb.com/rooms/sky-loft-penthouse',
    featured: false,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Rooftop Terrace', 'City View', 'Gym', 'Pool'],
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
  '10': {
    id: '10',
    name: 'Cityscape Studio',
    slug: 'cityscape-studio',
    type: 'studio',
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    size: '45',
    description: 'Experience modern city living at its finest in this beautifully designed studio unit located in the heart of Iloilo Business Park.',
    short_description: 'Modern studio with stunning city views. Perfect for business travelers and couples.',
    location: 'Iloilo Business Park',
    pricePerNight: '3500',
    airbnbUrl: 'https://airbnb.com/rooms/cityscape-studio',
    featured: true,
    active: true,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Smart TV', 'Workspace', 'City View', '24/7 Security', 'Gym Access'],
    photos: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80',
    ],
    icalUrl: '',
    featuredPhotoIndex: 0,
  },
};

export const DEFAULT_SETTINGS = {
  logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=200&q=80', // Professional building logo
  footerLogo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=200&q=80',
  heroBackground: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&q=80', // Beautiful property hero image
  aboutImage: 'https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80',
  contactImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  favicon: '/favicon.ico',

  heroBadgeText: 'Premium Short-Term Rentals',
  heroTitle: 'Your Cozy Escape in Iloilo City',
  heroSubtitle: 'Experience Comfort & Convenience',
  heroDescription: 'Discover our handpicked collection of premium condominiums offering modern amenities, stunning views, and prime locations across Iloilo City.',

  statsUnits: '9+',
  statsUnitsLabel: 'Premium Units',
  statsRating: '4.9',
  statsRatingLabel: 'Guest Rating',
  statsLocation: 'Iloilo',
  statsLocationLabel: 'City Center',

  highlyRatedTitle: 'Highly Rated',
  highlyRatedSubtitle: 'by our guests',
  highlyRatedImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',

  featuredTitle: 'Featured Properties',
  featuredSubtitle: 'Handpicked condominiums offering the perfect balance of comfort, convenience, and style.',

  phone: '+63 917 123 4567',
  email: 'info@cozycondo.net',
  address: 'Iloilo City, Philippines',
  website: 'https://cozycondo.net',
  facebookUrl: '',
  messengerUrl: '',
  checkinTime: '3:00 PM',
  checkoutTime: '11:00 AM',
  timezone: 'Asia/Manila',
  currency: 'PHP',
  faqs: [
    {
      id: '1',
      question: 'How do I make a reservation?',
      answer: 'You can make a reservation by contacting us directly through Facebook Messenger, phone, or email. We\'ll help you check availability and process your booking quickly.',
      order: 0
    },
    {
      id: '2',
      question: 'What are your check-in and check-out times?',
      answer: 'Check-in time is 3:00 PM and check-out time is 11:00 AM (Philippine Time). Early check-in or late check-out may be available upon request and subject to availability.',
      order: 1
    },
    {
      id: '3',
      question: 'Are your properties fully furnished?',
      answer: 'Yes, all our properties are fully furnished with modern amenities including WiFi, air conditioning, kitchen facilities, linens, towels, and essential household items.',
      order: 2
    },
    {
      id: '4',
      question: 'Do you provide airport transfers?',
      answer: 'While we don\'t provide direct airport transfer services, we can help arrange transportation or provide recommendations for reliable taxi services and ride-sharing options.',
      order: 3
    },
    {
      id: '5',
      question: 'What is your cancellation policy?',
      answer: 'Our cancellation policy varies depending on the booking terms and timing. Please contact us directly to discuss your specific situation and we\'ll work with you to find a fair solution.',
      order: 4
    },
    {
      id: '6',
      question: 'Are pets allowed in the properties?',
      answer: 'Pet policies vary by property and building regulations. Please let us know if you\'re traveling with pets when making your inquiry, and we\'ll check availability at pet-friendly locations.',
      order: 5
    }
  ],
  companyName: 'Cozy Condo'
};

export function getProductionFallbackProperties() {
  return DEFAULT_PROPERTIES;
}

export function getProductionFallbackSettings() {
  return DEFAULT_SETTINGS;
}